### ISSUE TITLE
Segelflugstarts EDRK massiv unterschätzt

### ISSUE THREAD

**Issue by FoxtrotSierra6829** [weglide/flugfeld#1]
Ich weiß nicht, wie es zu der geringen angezeigten Anzahl an Starts in Koblenz kam, aber die sind mit 461 (2019: 238) definitiv viel zu gering. Sieht ja so aus, als ob bei uns am Platz nicht's los wäre :D

Hier mal die richtigen Zahlen:

![Segelflugstarts EDRK 2019](https://user-images.githubusercontent.com/50082450/103155836-5a96b680-47a3-11eb-886c-b18b9b3e0926.jpg)
2019: 1829 Segelflugstarts

![Segelflugstarts EDRK 2020](https://user-images.githubusercontent.com/50082450/103155853-844fdd80-47a3-11eb-9e26-cf759c098e4d.jpg)
2020: 1801 Segelflugstarts

Wenn Zeit dafür ist, wäre es schön, wenn das auf ein einigermaßen realistisches Niveau angehoben wird :)

**Comment by moldhouse** [comment]
Hi Florian, thanks for the notice. I understand that the total number of starts is higher than the number we provide. We calculate the number of launches on base of publicly available data and do not include every start (e.g. 'Platzrunde') in our counting method. Maybe we should change the naming to be more precise as to what we mean by 'flights'. If we manually adjust the numbers only for Koblenz, it will appear more prominent in the map, even though other airfields might be more 'important' for cross country soaring.
